### ISSUE TITLE
Fix problem with trash in file  config

### ISSUE THREAD

**Issue by asalnikov** [clustbench/network-tests2#14]
It leave 
`ANT=@ANT@
JAVAC=@JAVAC@
JAR=@JAR@
GOALS= network_test  network_test
`

**Comment by igormunkin** [comment]
GOALS variable should not be removed because it is required for other components too

**Comment by igormunkin** [comment]
[Merged](https://github.com/clustbench/network-tests2/commit/3173e70078408035dace8ce9099e022b1bc48318) into master branch.

**Comment by asalnikov** [comment]
Игорь, а можешь ещё коментариев там в код configure.ac добавить, а то воспринимается сложновато уже.

**Comment by igormunkin** [comment]
@asalnikov, добавил в configure.ac и в ac-macros/ax-macros.m4
