### ISSUE TITLE
make install иногда фейлится при кол-ве параллельных воркеров больше единицы

### ISSUE THREAD

**Issue by philip-bl** [clustbench/network-tests2#18]
Качаю `network-tests`, создаю файл *configure*, конфигурю, делаю `make -j3 all` - все ок. Делаю `make -j3 install` - все не ок. Кажется, криво прописаны зависимости. Он пытается скопировать файлы в папки до того, как эти папки создает. Хорошо бы исправить. Мне лень исправлять, поэтому буду костыльно обходить проблему, вызывая `make -j1 install`.

**Comment by igormunkin** [comment]
Для того, чтобы понять в чем проблема, достаточно посмотреть на компоненты правила `install` в корневом Makefile.in:
```
install: prepare_install install_core $(GOALS) $(INSTALL_DIR)/config install_doc
```
КО, заявляет, что выполняя сборку более чем 1 воркером, практически (от слова совсем) неизбежно наличие ситуации гонки, в котором директории, инициализируемые правилом `prepare_install`, могут отсутствовать до выполнения правила `install_core`.

В любом случае, глобально эту ситуацию обойти проблематично, потому что длина GOALS варьируется в зависимости от комбинации ключей `./configure`, а все остальные компоненты так или иначе зависят от успешного исполнения `prepare_install`. _C'est La Vie_.

**Comment by philip-bl** [comment]
Мне на стэковерфлоу предложили такое [решение](http://stackoverflow.com/a/42144325/271388):

```
.NOTPARALLEL:
    install
```

**Comment by asalnikov** [comment]
Игорь, проверь пожалуйста на работоспособность .NOTPARALLEL

**Comment by igormunkin** [comment]
@asalnikov, вроде стало лучше

**Comment by asalnikov** [comment]
Внёс в Мастер. Побочную ветку удаляю.
