### ISSUE TITLE
Configure with autoconf 2.69 problem

### ISSUE THREAD

**Issue by asalnikov** [clustbench/network-tests2#23]
bash-4.1$ autoconf --version
autoconf (GNU Autoconf) 2.69
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+/Autoconf: GNU GPL version 3 or later
<http://gnu.org/licenses/gpl.html>, <http://gnu.org/licenses/exceptions.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by David J. MacKenzie and Akim 

autoconf configure.ac > ./configure

./configure: line 2238: syntax error near unexpected token `qt-gui,'
./configure: line 2238: `AX_ARG_ENABLE(qt-gui, " network_viewer_qt_v2 ", "",'

**Comment by igormunkin** [comment]
You have to run `aclocal` for generating aclocal.m4, required for external m4 files before running `autoconf`. Thus, Makefile generating consists of next commands
```bash
$ aclocal
$ autoconf configure.ac > ./configure
$ ./configure
```
You can find more information about `aclocal` invocation [here](https://www.gnu.org/software/automake/manual/html_node/aclocal-Invocation.html)
